vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        image_post:
            uri_prefix: /images/dynamic/posts
            upload_destination: '%kernel.project_dir%/public/images/dynamic/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
